/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewRoleRouteImport } from './routes/interview.$role'
import { Route as ReportRoleRouteImport } from './routes/report.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoleRoute = InterviewRoleRouteImport.update({
  id: '/interview/$role',
  path: '/interview/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoleRoute = ReportRoleRouteImport.update({
  id: '/report/$role',
  path: '/report/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interview/$role': typeof InterviewRoleRoute
  '/report/$role': typeof ReportRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview/$role': typeof InterviewRoleRoute
  '/report/$role': typeof ReportRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interview/$role': typeof InterviewRoleRoute
  '/report/$role': typeof ReportRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interview/$role' | '/report/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interview/$role' | '/report/$role'
  id: '__root__' | '/' | '/interview/$role' | '/report/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewRoleRoute: typeof InterviewRoleRoute
  ReportRoleRoute: typeof ReportRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$role': {
      id: '/interview/$role'
      path: '/interview/$role'
      fullPath: '/interview/$role'
      preLoaderRoute: typeof InterviewRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$role': {
      id: '/report/$role'
      path: '/report/$role'
      fullPath: '/report/$role'
      preLoaderRoute: typeof ReportRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewRoleRoute: InterviewRoleRoute,
  ReportRoleRoute: ReportRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
